version: "3.8"

services:
  psql:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_USER: ${DB_USERNAME:-user}
      POSTGRES_DB: ${DB_DATABASE:-db}
    restart: always
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - psql_volume:/var/lib/postgresql/data

volumes:
  psql_volume:
