# fly.toml app configuration file generated for nbapi-api on 2024-09-08T16:42:59+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nbapi-api'
primary_region = 'ams'

[build]
  [build.args]
    GO_VERSION = '1.23.1'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
