// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Advanced struct {
	ID         int32
	Per        float32
	TsPercent  float32
	_3pAr      float32
	FTr        float32
	OrbPercent float32
	DrbPercent float32
	TrbPercent float32
	AstPercent float32
	StlPercent float32
	BlkPercent float32
	TovPercent float32
	UsgPercent float32
	Ows        float32
	Dws        float32
	Ws         float32
	Ws48       float32
	Obpm       float32
	Dbpm       float32
	Bpm        float32
	Vorp       float32
}

type AllStar struct {
	PlayerID   int32
	SeasonYear int32
	Teamname   pgtype.Text
	Replaced   pgtype.Bool
}

type AllTeam struct {
	PlayerID   int32
	SeasonYear int32
	Type       string
	TeamNumber string
}

type AllTeamsVoting struct {
	PlayerID   int32
	SeasonYear int32
	TeamID     int32
	PtsWon     int32
	PtsMax     int32
	Share      float32
	_1stTeam   int32
	_2ndTeam   int32
	_3rdTeam   int32
	Type       string
}

type OpponentsPer100Possesion struct {
	TeamID     int32
	Per100ID   int32
	SeasonYear int32
}

type OpponentsPerGame struct {
	TeamID     int32
	PerGameID  int32
	SeasonYear int32
}

type OpponentsTotal struct {
	TeamID     int32
	TotalID    int32
	SeasonYear int32
}

type Per100Possesion struct {
	ID   int32
	Fg   float32
	Fga  float32
	_3p  int32
	_3pa int32
	_2p  int32
	_2pa int32
	Ft   float32
	Fta  float32
	Orb  float32
	Drb  float32
	Trb  float32
	Stl  float32
	Blk  float32
	Ast  float32
	Tov  float32
	Pf   float32
	Pts  float32
	ORtg float32
	DRtg float32
}

type Per36 struct {
	PlayerID   int32
	SeasonYear int32
	Fg         float32
	Fga        float32
	_3p        float32
	_3pa       float32
	_2p        float32
	_2pa       float32
	Ft         float32
	Fta        float32
	Orb        float32
	Drb        float32
	Trb        float32
	Stl        float32
	Blk        float32
	Ast        float32
	Tov        float32
	Pf         float32
	Pts        float32
}

type PerGame struct {
	ID         int32
	Fg         float32
	Fga        float32
	_3p        int32
	_3pa       int32
	_2p        int32
	_2pa       int32
	Ft         float32
	Fta        float32
	Orb        float32
	Drb        float32
	Trb        float32
	Stl        float32
	Blk        float32
	Ast        float32
	Tov        float32
	Pf         float32
	Pts        float32
	Mp         float32
	FgPercent  float32
	_2pPercent float32
	_3pPercent float32
	EfgPercent float32
}

type Player struct {
	ID       int32
	Fullname string
}

type PlayerAdvanced struct {
	PlayerID   int32
	AdvancedID int32
	SeasonYear int32
}

type PlayerPer100Possesion struct {
	PlayerID   int32
	Per100ID   int32
	SeasonYear int32
}

type PlayerPerGame struct {
	PlayerID   int32
	PerGameID  int32
	SeasonYear int32
}

type PlayerTeam struct {
	PlayerID   int32
	TeamID     int32
	SeasonYear int32
	Age        int32
	Experience int32
	Position   string
}

type PlayerTotal struct {
	PlayerID   int32
	TotalID    int32
	SeasonYear int32
}

type Team struct {
	ID       int32
	Fullname string
	Abbr     string
}

type TeamPer100Possesion struct {
	TeamID     int32
	Per100ID   int32
	SeasonYear int32
}

type TeamPerGame struct {
	TeamID     int32
	PerGameID  int32
	SeasonYear int32
}

type TeamTotal struct {
	TeamID     int32
	TotalID    int32
	SeasonYear int32
}

type Total struct {
	ID   int32
	Gp   int32
	Gs   pgtype.Int4
	Mp   int32
	Fg   int32
	Fga  int32
	_3p  int32
	_3pa int32
	_2p  int32
	_2pa int32
	Ft   int32
	Fta  int32
	Orb  int32
	Drb  int32
	Trb  int32
	Stl  int32
	Blk  int32
	Ast  int32
	Tov  int32
	Pf   int32
	Pts  int32
}
