// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: players.sql

package sqlc

import (
	"context"
)

const getAllStars = `-- name: GetAllStars :many
select playerfullname, season_year, teamname, replaced from all_stars where lower(playerFullName) like '%' || lower($1) || '%'  and season_year between $2 and $3
`

type GetAllStarsParams struct {
	Lower        string `json:"lower"`
	SeasonYear   int32  `json:"season_year"`
	SeasonYear_2 int32  `json:"season_year_2"`
}

func (q *Queries) GetAllStars(ctx context.Context, arg GetAllStarsParams) ([]AllStar, error) {
	rows, err := q.db.Query(ctx, getAllStars, arg.Lower, arg.SeasonYear, arg.SeasonYear_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AllStar
	for rows.Next() {
		var i AllStar
		if err := rows.Scan(
			&i.Playerfullname,
			&i.SeasonYear,
			&i.Teamname,
			&i.Replaced,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTeams = `-- name: GetAllTeams :many
SELECT player_id, season_year, type, team_number, id, fullname FROM all_teams JOIN player on player.id = all_teams.player_id and season_year BETWEEN $1 and $2
`

type GetAllTeamsParams struct {
	SeasonYear   int32 `json:"season_year"`
	SeasonYear_2 int32 `json:"season_year_2"`
}

type GetAllTeamsRow struct {
	PlayerID   int32  `json:"player_id"`
	SeasonYear int32  `json:"season_year"`
	Type       string `json:"type"`
	TeamNumber string `json:"team_number"`
	ID         int32  `json:"id"`
	Fullname   string `json:"fullname"`
}

func (q *Queries) GetAllTeams(ctx context.Context, arg GetAllTeamsParams) ([]GetAllTeamsRow, error) {
	rows, err := q.db.Query(ctx, getAllTeams, arg.SeasonYear, arg.SeasonYear_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllTeamsRow
	for rows.Next() {
		var i GetAllTeamsRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.SeasonYear,
			&i.Type,
			&i.TeamNumber,
			&i.ID,
			&i.Fullname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTeamsType = `-- name: GetAllTeamsType :many
SELECT player_id, season_year, type, team_number, id, fullname FROM all_teams JOIN player on player.id = all_teams.player_id where "type" = $1 and season_year BETWEEN $2 and $3
`

type GetAllTeamsTypeParams struct {
	Type         string `json:"type"`
	SeasonYear   int32  `json:"season_year"`
	SeasonYear_2 int32  `json:"season_year_2"`
}

type GetAllTeamsTypeRow struct {
	PlayerID   int32  `json:"player_id"`
	SeasonYear int32  `json:"season_year"`
	Type       string `json:"type"`
	TeamNumber string `json:"team_number"`
	ID         int32  `json:"id"`
	Fullname   string `json:"fullname"`
}

func (q *Queries) GetAllTeamsType(ctx context.Context, arg GetAllTeamsTypeParams) ([]GetAllTeamsTypeRow, error) {
	rows, err := q.db.Query(ctx, getAllTeamsType, arg.Type, arg.SeasonYear, arg.SeasonYear_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllTeamsTypeRow
	for rows.Next() {
		var i GetAllTeamsTypeRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.SeasonYear,
			&i.Type,
			&i.TeamNumber,
			&i.ID,
			&i.Fullname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerAdvanced = `-- name: GetPlayerAdvanced :many
select advanced.id, advanced.per, advanced.ts_percent, advanced.p_ar3, advanced.f_tr, advanced.orb_percent, advanced.drb_percent, advanced.trb_percent, advanced.ast_percent, advanced.stl_percent, advanced.blk_percent, advanced.tov_percent, advanced.usg_percent, advanced.ows, advanced.dws, advanced.ws, advanced.ws48, advanced.obpm, advanced.dbpm, advanced.bpm, advanced.vorp from player
  inner join player_advanced on player.id = player_advanced.player_id
  inner join advanced on player_advanced.advanced_id = advanced.id
  where player.id = $1
  and player_advanced.season_year between $2 and $3
`

type GetPlayerAdvancedParams struct {
	ID           int32 `json:"id"`
	SeasonYear   int32 `json:"season_year"`
	SeasonYear_2 int32 `json:"season_year_2"`
}

func (q *Queries) GetPlayerAdvanced(ctx context.Context, arg GetPlayerAdvancedParams) ([]Advanced, error) {
	rows, err := q.db.Query(ctx, getPlayerAdvanced, arg.ID, arg.SeasonYear, arg.SeasonYear_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Advanced
	for rows.Next() {
		var i Advanced
		if err := rows.Scan(
			&i.ID,
			&i.Per,
			&i.TsPercent,
			&i.PAr3,
			&i.FTr,
			&i.OrbPercent,
			&i.DrbPercent,
			&i.TrbPercent,
			&i.AstPercent,
			&i.StlPercent,
			&i.BlkPercent,
			&i.TovPercent,
			&i.UsgPercent,
			&i.Ows,
			&i.Dws,
			&i.Ws,
			&i.Ws48,
			&i.Obpm,
			&i.Dbpm,
			&i.Bpm,
			&i.Vorp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerAllTeams = `-- name: GetPlayerAllTeams :many
SELECT player_id, season_year, type, team_number, id, fullname FROM all_teams JOIN player on player.id = all_teams.player_id where player_id = $1 and season_year BETWEEN $2 and $3
`

type GetPlayerAllTeamsParams struct {
	PlayerID     int32 `json:"player_id"`
	SeasonYear   int32 `json:"season_year"`
	SeasonYear_2 int32 `json:"season_year_2"`
}

type GetPlayerAllTeamsRow struct {
	PlayerID   int32  `json:"player_id"`
	SeasonYear int32  `json:"season_year"`
	Type       string `json:"type"`
	TeamNumber string `json:"team_number"`
	ID         int32  `json:"id"`
	Fullname   string `json:"fullname"`
}

func (q *Queries) GetPlayerAllTeams(ctx context.Context, arg GetPlayerAllTeamsParams) ([]GetPlayerAllTeamsRow, error) {
	rows, err := q.db.Query(ctx, getPlayerAllTeams, arg.PlayerID, arg.SeasonYear, arg.SeasonYear_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlayerAllTeamsRow
	for rows.Next() {
		var i GetPlayerAllTeamsRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.SeasonYear,
			&i.Type,
			&i.TeamNumber,
			&i.ID,
			&i.Fullname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerAwardWinners = `-- name: GetPlayerAwardWinners :many
SELECT player_id, season_year, award, pts_won, pts_max, share, winner
FROM player_awards as pa
WHERE (pa.season_year, pa.award, pa.share) IN (
    SELECT season_year, award, MAX(share) AS max_share
    FROM player_awards px
    GROUP BY px.season_year, px.award
    HAVING px.season_year BETWEEN $1 AND $2
)
`

type GetPlayerAwardWinnersParams struct {
	SeasonYear   int32 `json:"season_year"`
	SeasonYear_2 int32 `json:"season_year_2"`
}

func (q *Queries) GetPlayerAwardWinners(ctx context.Context, arg GetPlayerAwardWinnersParams) ([]PlayerAward, error) {
	rows, err := q.db.Query(ctx, getPlayerAwardWinners, arg.SeasonYear, arg.SeasonYear_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlayerAward
	for rows.Next() {
		var i PlayerAward
		if err := rows.Scan(
			&i.PlayerID,
			&i.SeasonYear,
			&i.Award,
			&i.PtsWon,
			&i.PtsMax,
			&i.Share,
			&i.Winner,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerAwards = `-- name: GetPlayerAwards :many
SELECT player_id, season_year, award, pts_won, pts_max, share, winner FROM player_awards where player_id = $1 and season_year BETWEEN $2 and $3
`

type GetPlayerAwardsParams struct {
	PlayerID     int32 `json:"player_id"`
	SeasonYear   int32 `json:"season_year"`
	SeasonYear_2 int32 `json:"season_year_2"`
}

func (q *Queries) GetPlayerAwards(ctx context.Context, arg GetPlayerAwardsParams) ([]PlayerAward, error) {
	rows, err := q.db.Query(ctx, getPlayerAwards, arg.PlayerID, arg.SeasonYear, arg.SeasonYear_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlayerAward
	for rows.Next() {
		var i PlayerAward
		if err := rows.Scan(
			&i.PlayerID,
			&i.SeasonYear,
			&i.Award,
			&i.PtsWon,
			&i.PtsMax,
			&i.Share,
			&i.Winner,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerById = `-- name: GetPlayerById :one
select id, fullname from player where id = $1
`

func (q *Queries) GetPlayerById(ctx context.Context, id int32) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayerById, id)
	var i Player
	err := row.Scan(&i.ID, &i.Fullname)
	return i, err
}

const getPlayerPer100 = `-- name: GetPlayerPer100 :many
select per_100_possesions.id, per_100_possesions.fg, per_100_possesions.fga, per_100_possesions.p3, per_100_possesions.pa3, per_100_possesions.p2, per_100_possesions.pa2, per_100_possesions.ft, per_100_possesions.fta, per_100_possesions.orb, per_100_possesions.drb, per_100_possesions.trb, per_100_possesions.stl, per_100_possesions.blk, per_100_possesions.ast, per_100_possesions.tov, per_100_possesions.pf, per_100_possesions.pts, per_100_possesions.o_rtg, per_100_possesions.d_rtg from player
  inner join player_per_100_possesions on player.id = player_per_100_possesions.player_id
  inner join per_100_possesions on player_per_100_possesions.per_100_id = per_100_possesions.id
  where player.id = $1
  and player_per_100_possesions.season_year between $2 and $3
`

type GetPlayerPer100Params struct {
	ID           int32 `json:"id"`
	SeasonYear   int32 `json:"season_year"`
	SeasonYear_2 int32 `json:"season_year_2"`
}

func (q *Queries) GetPlayerPer100(ctx context.Context, arg GetPlayerPer100Params) ([]Per100Possesion, error) {
	rows, err := q.db.Query(ctx, getPlayerPer100, arg.ID, arg.SeasonYear, arg.SeasonYear_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Per100Possesion
	for rows.Next() {
		var i Per100Possesion
		if err := rows.Scan(
			&i.ID,
			&i.Fg,
			&i.Fga,
			&i.P3,
			&i.Pa3,
			&i.P2,
			&i.Pa2,
			&i.Ft,
			&i.Fta,
			&i.Orb,
			&i.Drb,
			&i.Trb,
			&i.Stl,
			&i.Blk,
			&i.Ast,
			&i.Tov,
			&i.Pf,
			&i.Pts,
			&i.ORtg,
			&i.DRtg,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerPer36 = `-- name: GetPlayerPer36 :many
select player_per_36.player_id, player_per_36.season_year, player_per_36.fg, player_per_36.fga, player_per_36.p3, player_per_36.pa3, player_per_36.p2, player_per_36.pa2, player_per_36.ft, player_per_36.fta, player_per_36.orb, player_per_36.drb, player_per_36.trb, player_per_36.stl, player_per_36.blk, player_per_36.ast, player_per_36.tov, player_per_36.pf, player_per_36.pts from player
  inner join player_per_36 on player_per_36.player_id = player.id
  where player.id = $1
  and player_per_36.season_year between $2 and $3
`

type GetPlayerPer36Params struct {
	ID           int32 `json:"id"`
	SeasonYear   int32 `json:"season_year"`
	SeasonYear_2 int32 `json:"season_year_2"`
}

func (q *Queries) GetPlayerPer36(ctx context.Context, arg GetPlayerPer36Params) ([]PlayerPer36, error) {
	rows, err := q.db.Query(ctx, getPlayerPer36, arg.ID, arg.SeasonYear, arg.SeasonYear_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlayerPer36
	for rows.Next() {
		var i PlayerPer36
		if err := rows.Scan(
			&i.PlayerID,
			&i.SeasonYear,
			&i.Fg,
			&i.Fga,
			&i.P3,
			&i.Pa3,
			&i.P2,
			&i.Pa2,
			&i.Ft,
			&i.Fta,
			&i.Orb,
			&i.Drb,
			&i.Trb,
			&i.Stl,
			&i.Blk,
			&i.Ast,
			&i.Tov,
			&i.Pf,
			&i.Pts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerPerGame = `-- name: GetPlayerPerGame :many
select per_game.id, per_game.mp, per_game.fg, per_game.fga, per_game.fg_percent, per_game.p3, per_game.pa3, per_game.p_percent3, per_game.p2, per_game.pa2, per_game.p_percent2, per_game.efg_percent, per_game.ft, per_game.fta, per_game.ft_percent, per_game.orb, per_game.drb, per_game.trb, per_game.ast, per_game.stl, per_game.blk, per_game.tov, per_game.pf, per_game.pts from player
  inner join player_per_game on player.id = player_per_game.player_id
  inner join per_game on player_per_game.per_game_id = per_game.id
  where player.id = $1
  and player_per_game.season_year between $2 and $3
`

type GetPlayerPerGameParams struct {
	ID           int32 `json:"id"`
	SeasonYear   int32 `json:"season_year"`
	SeasonYear_2 int32 `json:"season_year_2"`
}

func (q *Queries) GetPlayerPerGame(ctx context.Context, arg GetPlayerPerGameParams) ([]PerGame, error) {
	rows, err := q.db.Query(ctx, getPlayerPerGame, arg.ID, arg.SeasonYear, arg.SeasonYear_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PerGame
	for rows.Next() {
		var i PerGame
		if err := rows.Scan(
			&i.ID,
			&i.Mp,
			&i.Fg,
			&i.Fga,
			&i.FgPercent,
			&i.P3,
			&i.Pa3,
			&i.PPercent3,
			&i.P2,
			&i.Pa2,
			&i.PPercent2,
			&i.EfgPercent,
			&i.Ft,
			&i.Fta,
			&i.FtPercent,
			&i.Orb,
			&i.Drb,
			&i.Trb,
			&i.Ast,
			&i.Stl,
			&i.Blk,
			&i.Tov,
			&i.Pf,
			&i.Pts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerShooting = `-- name: GetPlayerShooting :many
select player_shooting.season_year, player_shooting.player_id, player_shooting.avg_dist_fga, player_shooting.percent_fga_from_2p_range, player_shooting.percent_fga_from_0_3_range, player_shooting.percent_fga_from_3_10_range, player_shooting.percent_fga_from_10_16_range, player_shooting.percent_fga_from_16_3p_range, player_shooting.percent_fga_from_3p_range, player_shooting.fg_percent_from_2p_range, player_shooting.fg_percent_from_0_3_range, player_shooting.fg_percent_from_3_10_range, player_shooting.fg_percent_from_10_16_range, player_shooting.fg_percent_from_16_3p_range, player_shooting.fg_percent_from_3p_range, player_shooting.percent_assisted_2p_fg, player_shooting.percent_assisted_3p_fg, player_shooting.percent_dunks_of_fga, player_shooting.num_of_dunks, player_shooting.percent_corner_3s_of_3pa, player_shooting.corner_3_point_percent, player_shooting.num_heaves_attempted, player_shooting.num_heaves_made from player
  inner join player_shooting on player_shooting.player_id = player.id
  where player.id = $1
  and player_shooting.season_year between $2 and $3
`

type GetPlayerShootingParams struct {
	ID           int32 `json:"id"`
	SeasonYear   int32 `json:"season_year"`
	SeasonYear_2 int32 `json:"season_year_2"`
}

func (q *Queries) GetPlayerShooting(ctx context.Context, arg GetPlayerShootingParams) ([]PlayerShooting, error) {
	rows, err := q.db.Query(ctx, getPlayerShooting, arg.ID, arg.SeasonYear, arg.SeasonYear_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlayerShooting
	for rows.Next() {
		var i PlayerShooting
		if err := rows.Scan(
			&i.SeasonYear,
			&i.PlayerID,
			&i.AvgDistFga,
			&i.PercentFgaFrom2pRange,
			&i.PercentFgaFrom03Range,
			&i.PercentFgaFrom310Range,
			&i.PercentFgaFrom1016Range,
			&i.PercentFgaFrom163pRange,
			&i.PercentFgaFrom3pRange,
			&i.FgPercentFrom2pRange,
			&i.FgPercentFrom03Range,
			&i.FgPercentFrom310Range,
			&i.FgPercentFrom1016Range,
			&i.FgPercentFrom163pRange,
			&i.FgPercentFrom3pRange,
			&i.PercentAssisted2pFg,
			&i.PercentAssisted3pFg,
			&i.PercentDunksOfFga,
			&i.NumOfDunks,
			&i.PercentCorner3sOf3pa,
			&i.Corner3PointPercent,
			&i.NumHeavesAttempted,
			&i.NumHeavesMade,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerTotals = `-- name: GetPlayerTotals :many
select totals.id, totals.gp, totals.gs, totals.mp, totals.fg, totals.fga, totals.p3, totals.pa3, totals.p2, totals.pa2, totals.ft, totals.fta, totals.orb, totals.drb, totals.trb, totals.stl, totals.blk, totals.ast, totals.tov, totals.pf, totals.pts from player
inner join player_totals on player.id = player_totals.player_id
inner join totals on totals.id = player_totals.total_id
where player.id = $1
and player_totals.season_year between $2 and $3
`

type GetPlayerTotalsParams struct {
	ID           int32 `json:"id"`
	SeasonYear   int32 `json:"season_year"`
	SeasonYear_2 int32 `json:"season_year_2"`
}

func (q *Queries) GetPlayerTotals(ctx context.Context, arg GetPlayerTotalsParams) ([]Total, error) {
	rows, err := q.db.Query(ctx, getPlayerTotals, arg.ID, arg.SeasonYear, arg.SeasonYear_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Total
	for rows.Next() {
		var i Total
		if err := rows.Scan(
			&i.ID,
			&i.Gp,
			&i.Gs,
			&i.Mp,
			&i.Fg,
			&i.Fga,
			&i.P3,
			&i.Pa3,
			&i.P2,
			&i.Pa2,
			&i.Ft,
			&i.Fta,
			&i.Orb,
			&i.Drb,
			&i.Trb,
			&i.Stl,
			&i.Blk,
			&i.Ast,
			&i.Tov,
			&i.Pf,
			&i.Pts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayers = `-- name: GetPlayers :many
select
    id, fullname
from
    player
where
    lower(fullName) like '%' || lower($1) || '%' and
    id >= $2
    order by id
    limit $3 + 1
`

type GetPlayersParams struct {
	Search   string      `json:"search"`
	Cursor   int32       `json:"cursor"`
	PageSize interface{} `json:"page_size"`
}

func (q *Queries) GetPlayers(ctx context.Context, arg GetPlayersParams) ([]Player, error) {
	rows, err := q.db.Query(ctx, getPlayers, arg.Search, arg.Cursor, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Player
	for rows.Next() {
		var i Player
		if err := rows.Scan(&i.ID, &i.Fullname); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
